project_id = "fzzpkdaaewrpaaaaudmh"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
site_url = "https://fzzpkdaaewrpaaaaudmh.supabase.co"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[edge-runtime]
policy = "per_worker"
inspector_port = 8083